Create/content editor challenge
croct-tech/challenges pull request #19
Opened 2022-08-12 17:07 UTC by Koemyy

What has been done?
Create new challenge.

How it has been done?
Create challenge for Content Editor.

2022-08-12 19:04 UTC, amorimjuliana requested changes

2022-08-12 19:04 UTC, amorimjuliana commented on content-editor/README.md
> +You received two blog posts written by one of our freelance writers. One is about [user-generated content](https://docs.google.com/document/d/1Xi2kG4H6_Ou0SzdsugWMRnbWsZmfWqerrXXIWUefUOE/edit), and t
```suggestion
You received two blog posts written by one of our freelance writers. One is about [user-generated content](https://docs.google.com/document/d/160yeu9ygOQFk6cGWMLRwvua6DSsB1--SLuykjel5suY/edit?usp=sharing), and the other is about how [machine learning](https://docs.google.com/document/d/1zlcr0X6Xf9-tx87wdwm06EBxvGK6DklTvUyT52LvRnk/edit?usp=sharing) can leverage personalization marketing.
```

2022-08-12 19:04 UTC, amorimjuliana commented on content-editor/README.md
> +To help you understand the changes we usually make, we also provide you with [previously reviewed](https://docs.google.com/document/d/1QhDgKheJak8htgUxjSZZD9zOP2_RfFWjEfmepv8Ezqk/edit) pieces of cont
```suggestion
To help you understand the changes we usually make, we also provide you with [previously reviewed](https://docs.google.com/document/d/1ITny1TNSvEZ_9o2BK-B9ELjMJxRoTofMTaibFHQFk2Q/edit?usp=sharing) pieces of content with highlighted adjustments our content marketing team suggested.
```

2022-08-12 21:52 UTC, amorimjuliana approved these changes

2022-08-15 18:47 UTC, marcospassos approved these changes

2022-08-15 18:48 UTC, merged